# These settings are synced to GitHub by https://probot.github.io/apps/settings/

branches:
  - name: main
    # https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection
    protection:
      allow_force_pushes: false
      enforce_admins: true
      required_linear_history: false
      required_pull_request_reviews: null
      required_status_checks:
        contexts:
          - "check format [aarch64-darwin]"
          - "check format [aarch64-linux]"
          - "check format [x86_64-linux]"
          - "devShell default [aarch64-darwin]"
          - "devShell default [aarch64-linux]"
          - "devShell default [x86_64-linux]"
          - "homeConfiguration aarch64-darwin-dhall-bhat-example"
          - "homeConfiguration aarch64-linux-dhall-bhat-example"
          - "homeConfiguration x86_64-linux-dhall-bhat-example"
          - "package default [aarch64-darwin]"
          - "package default [aarch64-linux]"
          - "package default [x86_64-linux]"
          - "package dhall-bhat [aarch64-darwin]"
          - "package dhall-bhat [aarch64-linux]"
          - "package dhall-bhat [x86_64-linux]"
        strict: false
      restrictions:
        apps: []

labels:
  - color: "#d73a4a"
    description: Something isn’t working
    name: bug
  - color: "#0075ca"
    description: Improvements or additions to documentation
    name: documentation
  - color: "#a2eeef"
    description: New feature or request
    name: enhancement
  - color: "#7057ff"
    description: Good for newcomers
    name: good first issue
  - color: "#008672"
    description: Extra attention is needed
    name: help wanted
  - color: "#d876e3"
    description: Further information is requested
    name: question
pages:
  build_type: "workflow"
  source:
    branch: "master"
# See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
repository:
  # homepage: https://example.github.io/
  # topics: development, nix-flakes, nix-templates
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: false
  default_branch: main
  delete_branch_on_merge: true
  description: Tasty meal of Dhall
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: true
  merge_commit_message: PR_BODY
  merge_commit_title: PR_TITLE
  name: dhall-bhat
  private: false
